name: Peremotes
author: PereCraft
version: 1.3
main: peremotes.Peremotes
description: Emotes di PereCraft
commands:
    peremotes:
        description: "Help page delle emotes"
        aliases: [pe]
        